MusicApp/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource  :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
end

MusicApp/app/models/album.rb
class Album < ActiveRecord::Base

  validates :title, :band_id, :record_type, presence: true

  has_many(
    :tracks,
    class_name: 'Track',
    primary_key: :id,
    foreign_key: :album_id,
    dependent: :destroy
  )
  belongs_to(
    :band,
    class_name: 'Band',
    primary_key: :id,
    foreign_key: :band_id
  )
end

MusicApp/app/models/band.rb
class Band < ActiveRecord::Base

  validates :name, presence: true
  
  has_many(
    :albums,
    class_name: 'Album',
    primary_key: :id,
    foreign_key: :band_id,
    dependent: :destroy
  )
end

MusicApp/app/models/track.rb
class Track < ActiveRecord::Base

  validates :song, :album_id, :track_type, presence: true

  belongs_to(
    :album,
    class_name: 'Album',
    primary_key: :id,
    foreign_key: :album_id
  )
end

MusicApp/app/models/user.rb
class User < ActiveRecord::Base

  attr_reader :password

  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: { message: "Must have a password" }
  validates :password, length: { minimum: 6 }, allow_nil: true

  after_initialize :ensure_session_token


  def self.find_by_credentials(email, pass)
    user = User.find_by_email(email)
    user if user && is_password(pass)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = generate_session_token
    save
    session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(pass)
    BCrypt::Password.new(password_digest).is_password?(pass)
  end


  private
  def ensure_session_token
    self.session_token ||= generate_session_token
  end

end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :force_login
  
  def new
    @album = Album.new
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      flash[:notice] = ["Created new album: #{@album.title}"]
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
    render :edit
  end

  def update
    @album = Album.new(album_params)

    if @album.save
      flash[:notice] = ["Edited: #{@album.title}"]
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    band_id = @album.band_id
    flash[:notice] = ["Deleted: #{@album.title}"]
    @album.delete
    redirect_to band_url(band_id)
  end
  private
  def album_params
    params.require(:album).permit(:title, :band_id, :record_type)
  end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def log_out!
    current_user.reset_session_token!
    @current_user = nil
    session[:session_token] = nil
  end

  def force_login
    unless logged_in?
      flash[:errors] = ["Sorry, must be logged in to view this page"]
      redirect_to new_session_url
    end
  end

end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :force_login

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      flash[:notice] = ["Created new band: #{@band.name}"]
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    @band = Band.find(params[:id])

    if @band.save
      flash[:notice] = ["Edited band: #{@band.name}"]
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end
  def update

  end

  def destroy
    @band = Band.find(params[:id])
    flash[:notice] = ["Deleted: #{@band.name}"]
    @band.delete
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_email(params[:user][:email])
    if @user && @user.is_password?(params[:user][:password])
      log_in!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end

end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :force_login

  def new
    @track = Track.new
    @albums = Album.all
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      flash[:notice] = ["Created new track: #{@track.song}"]
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Album.all
    render :edit
  end

  def update
    @track = Track.find(params[:id])

    if @track.save
      flash[:notice] = ["Edited: #{@track.song}"]
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    flash[:notice] = ["Deleted: #{@track.song}"]
    @track.delete
    redirect_to new_album_track_url
  end
  private
  def track_params
    params.require(:track).permit(:song, :album_id, :track_type, :lyrics)
  end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user)
      flash[:notice] = ["Thanks for signing up!"]
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end

  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper

  def authenticity_token
  html = "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>"
  html.html_safe
  end

end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/albums/_form.html.erb
<!--  Checking if album exists-->
<% unless album.persisted? %>
  <% action = albums_url %>
  <% value = "Create Album" %>

<% else %>
  <% action = album_url(album) %>
  <% value = "Edit Album" %>
<% end %>

<form action="<%= action %>" method="POST">
  <%= authenticity_token %>
  <% if album.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label>Title:
    <input type="text" name="album[title]" placeholder="<%= album.title || "title" %>">
  </label>
  <br><br>
  <label>Recorded by:
    <select name="album[band_id]">
      <option "selected">Select a Band</option>
      <% bands.each do |band| %>
      <option value="<%= band.id %>" <%= "selected" if  band.id == album.band_id %> ><%= band.name %></option>
      <% end %>
    </select>
  </label>
  <br><br>
  <label>Live recording
    <input type="radio" name="album[record_type]" value="LIVE" <%= "checked" if album.record_type == "LIVE" %>>
  </label>
  <label>Studio recording
    <input type="radio" name="album[record_type]" value="STUDIO" <%= "checked" if album.record_type == "LIVE" %>>
  </label>
  <br><br>
  <input type="submit" value="<%= value %>">
</form>

MusicApp/app/views/albums/edit.html.erb
<h1>Edit an Album:</h1>
<%= render "shared/errors" %>

<%= render partial: "form", locals: {album: @album, bands: @bands} %>

MusicApp/app/views/albums/new.html.erb
<h1>Add an Album:</h1>
<%= render "shared/errors" %>

<%= render partial: "form", locals: {album: @album, bands: @bands} %>

MusicApp/app/views/albums/show.html.erb
<h1><%= @album.title %> Album's Page </h1>
<%= render "shared/errors" %>
<!-- Edit/Delete links -->
<table>
  <tr>
    <form action="<%= edit_album_url %>" method="GET">
      <%= authenticity_token %>
      <input type="submit" value="Edit album">
    </form> &nbsp; &nbsp; &nbsp;
    <form action="<%= edit_album_url %>" method="POST">
      <%= authenticity_token %>
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Delete album">
    </form>
  </tr>
</table>
<!--  Band -->
<h3> Recorded by: "<%= @album.band.name %>" </h3>
<a href="<%= band_url(@album.band_id) %>">More albums from this artist</a>
<!--  Tracks -->
<h3>Tracks:</h3>
<table>
<% @album.tracks.each do |track| %>
  <tr>
    <td><%=track.song%></td>
    <td><form action="<%= edit_track_url %>" method="GET">
        <%= authenticity_token %>
        <input type="submit" value="Edit track">
        </form>
    </td>
    <td><form action="<%= edit_track_url %>" method="POST">
        <%= authenticity_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Delete track">
        </form>
    </td>
  </tr>
<% end %>
</table>
<a href="<%= new_album_track_url(@album) %>">Add Tracks</a>

MusicApp/app/views/bands/edit.html.erb
<h1>Edit band: <%= @band.name %></h1>
<%= render "shared/errors" %>
<form action="<%= band_url(band) %>" method="POST">
  <%= authenticity_token %>
  <input type="hidden" name="_method" value="PATCH">
  <label>Name:
    <input type="text" name="band[name]" value="<%= @band.name %>">
  </label>
  <br><br>
  <input type="submit" value="Edit Band">
</form>

MusicApp/app/views/bands/index.html.erb
<h1>All Bands</h1>

<h3>Bands:</h3>
<table>
<% @bands.each do |band| %>
  <tr>
    <td><a href="<%= band_url(band)%>"><%=band.name%></a></td>
    <td><form action="<%= edit_band_url(band) %>" method="GET">
        <%= authenticity_token %>
        <input type="submit" value="Edit band">
        </form>
    </td>
    <td><form action="<%= band_url(band) %>" method="POST">
        <%= authenticity_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Delete band">
        </form>
    </td>
  </tr>
<% end %>
</table>
<br>
<a href="<%= new_band_url %>">Add Bands</a>

MusicApp/app/views/bands/new.html.erb
<h1>Add a band:</h1>
<%= render "shared/errors" %>
<form action="<%= bands_url %>" method="POST">
  <%= authenticity_token %>
  <label>Name:
    <input type="text" name="band[name]" placeholder="band name">
  </label>
  <br><br>
  <input type="submit" value="Add Band">
</form>

MusicApp/app/views/bands/show.html.erb
<a href="<%=bands_url%>">Back to band index</a>
<br><br>
<h1><%= @band.name %>'s Page </h1>
<%= render "shared/errors" %>
<!-- Edit/Delete links -->
<table>
  <tr>
    <form action="<%= edit_band_url %>" method="GET">
      <%= authenticity_token %>
      <input type="submit" value="Edit band">
    </form> &nbsp; &nbsp; &nbsp;
    <form action="<%= band_url(@band) %>" method="POST">
      <%= authenticity_token %>
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Delete band">
    </form>
  </tr>
</table>&nbsp; &nbsp; &nbsp;
<!--  Album -->
<h3>Albums:</h3>
<table>
<% @band.albums.each do |album| %>
  <tr>
    <td> <a href="<%=album_url(album)%>"><%= album.title %></a></td>
    <td><form action="<%= edit_album_url %>" method="GET">
        <%= authenticity_token %>
        <input type="submit" value="Edit album">
        </form>
    </td>
    <td><form action="<%= album_url(album) %>" method="POST">
        <%= authenticity_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Delete album">
        </form>
    </td>
  </tr>
<% end %>
</table>
<br>
<a href="<%= new_band_album_url(@band) %>">Add Albums</a>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= csrf_meta_tags %>
</head>
<header>
  <% if current_user %>

    You're logged in using: <strong><%=current_user.email%></strong>
    <br><br>
    <form action="<%= session_url %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <%= authenticity_token %>
      <input type="submit" value="Log Out">
    </form>

  <% else %>
    <h3><a href="<%= new_session_url %>">Log In</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="<%= new_user_url %>">Create an Account</a></h3>
  <% end %>
<hr>
</header>
<body>

<%= yield %>

</body>
</html>

MusicApp/app/views/shared/_errors.html.erb
<% flash.each do |k, messages| %>
<ul>
  <% messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

MusicApp/app/views/tracks/_form.html.erb
<!--  Checking if album exists-->
<% unless track.persisted? %>
  <% action = tracks_url %>
  <% value = "Create Track" %>

<% else %>
  <% action = track_url(track) %>
  <% value = "Edit Track" %>
<% end %>

<form action="<%= action %>" method="POST">
  <%= authenticity_token %>
  <% if track.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label>Song Title:
    <input type="text" name="track[song]" placeholder="<%= track.song || "Song title" %>">
  </label>
  <br><br>
  <label>Listed In:
    <select name="track[album_id]">
      <option "selected">Select an Album</option>
      <% albums.each do |album| %>
      <option value="<%= album.id %>" <%= "selected" if  album.id == track.album_id %> ><%= album.title %></option>
      <% end %>
    </select>
  </label>
  <br><br>
  <label>Regular track
    <input type="radio" name="track[track_type]" value="REGULAR" <%= "checked" if track.track_type == "REGULAR" %>>
  </label>
  <label>Bonus track
    <input type="radio" name="track[track_type]" value="BONUS" <%= "checked" if track.track_type == "BONUS" %>>
  </label>
  <br><br>
  <label>
    <textarea><%=track.lyrics%></textarea>
  </label><br><br>
  <input type="submit" value="<%= value %>">
</form>

MusicApp/app/views/tracks/edit.html.erb
<h1>Edit a track:</h1>
<%= render "shared/errors" %>

<%= render partial: "form", locals: {track: @track, albums: @albums} %>

MusicApp/app/views/tracks/new.html.erb
<h1>Create a track:</h1>
<%= render "shared/errors" %>

<%= render partial: "form", locals: {track: @track, albums: @albums} %>

MusicApp/app/views/tracks/show.html.erb
<h1><%= @track.song %>'s Page </h1>
<%= render "shared/errors" %>
<!-- Edit/Delete links -->
<table>
  <tr>
    <form action="<%= edit_track_url %>" method="GET">
      <%= authenticity_token %>
      <input type="submit" value="Edit track">
    </form> &nbsp; &nbsp; &nbsp;
    <form action="<%= edit_track_url %>" method="POST">
      <%= authenticity_token %>
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Delete track">
    </form>
  </tr>
</table>
<!--  Album -->
<h3> Listed in: "<%= @track.album.title %>" </h3>
<a href="<%= album_url(@track.album_id) %>">More tracks from this album</a>
<!--  Lyrics -->
<h3>Lyrics:</h3>

MusicApp/app/views/users/new.html.erb
<h1>Create an account:</h1>
<%= render "shared/errors" %>
<form action="<%= users_url %>" method="POST">
  <%= authenticity_token %>
  <label>E-mail address:
    <input type="text" name="user[email]" placeholder="e-mail address">
  </label>
  <br><br>
  <label>Password:
    <input type="password" name="user[password]" placeholder="*******">
  </label>
  <br><br>
  <input type="submit" value="Create Account">
</form>

MusicApp/app/views/users/show.html.erb
<h1>Welcome to MusicApp!</h1>
<%= render "shared/errors" %>
<h3>E-mail Address:</h3>&nbsp;&nbsp; <%= current_user.email %>

<h3><a href="<%= bands_url%>">See All Bands</a></h3>